// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqNN8VFu5aUbvSE2_M6SHBo5mJTrw-1k',
    appId: '1:503974637196:web:79b60a642b1b88a90115a9',
    messagingSenderId: '503974637196',
    projectId: 'asu-carpooling-flutter',
    authDomain: 'asu-carpooling-flutter.firebaseapp.com',
    storageBucket: 'asu-carpooling-flutter.appspot.com',
    measurementId: 'G-EX3GGRZSTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPhZVDY0YJjn1wiBjISM-oJqpToPMBatk',
    appId: '1:503974637196:android:48602daf74e369440115a9',
    messagingSenderId: '503974637196',
    projectId: 'asu-carpooling-flutter',
    storageBucket: 'asu-carpooling-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5yBMwjGB5eyJdX1I90G4kLvZduxqEAVc',
    appId: '1:503974637196:ios:62d02d5d07dca5d30115a9',
    messagingSenderId: '503974637196',
    projectId: 'asu-carpooling-flutter',
    storageBucket: 'asu-carpooling-flutter.appspot.com',
    iosBundleId: 'com.example.carpoolFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5yBMwjGB5eyJdX1I90G4kLvZduxqEAVc',
    appId: '1:503974637196:ios:ddd83b27bd0244800115a9',
    messagingSenderId: '503974637196',
    projectId: 'asu-carpooling-flutter',
    storageBucket: 'asu-carpooling-flutter.appspot.com',
    iosBundleId: 'com.example.carpoolFlutter.RunnerTests',
  );
}
